### ISSUE TITLE
FOTO

### ISSUE THREAD

**Issue by smucci** [wutupake/ciao-cris#1]
![cris2](https://user-images.githubusercontent.com/5419846/122913573-e4da6480-d359-11eb-880a-e0957e0e58b6.jpeg)
![cris1](https://user-images.githubusercontent.com/5419846/122913577-e6a42800-d359-11eb-9e88-58143877d82a.jpeg)

**Comment by Fabryz** [comment]
![IMG_20150217_113352](https://user-images.githubusercontent.com/17748/122924513-1fe29500-d366-11eb-8406-01e72b1fdc01.jpg)

Issian mega dignitari

**Comment by soloistco** [comment]
![image](https://user-images.githubusercontent.com/35963087/122926869-95e7fb80-d368-11eb-99d0-c6e8ad9d6856.png)

**Comment by wutupake** [comment]
![Image from iOS](https://user-images.githubusercontent.com/596579/123935599-aa457d00-d994-11eb-9ff3-614d2a2aec3d.jpg)

**Comment by wutupake** [comment]
![_DSC1813](https://user-images.githubusercontent.com/596579/123939949-fdb9ca00-d998-11eb-95b4-5d9212ca5902.JPG)
![_DSC1872](https://user-images.githubusercontent.com/596579/123939952-feeaf700-d998-11eb-81fe-b3ed47113f95.JPG)
![IMG_20150217_112359](https://user-images.githubusercontent.com/596579/123939958-ff838d80-d998-11eb-9d03-3350c5a3f011.jpg)
![IMG_20180525_190417](https://user-images.githubusercontent.com/596579/123939963-00b4ba80-d999-11eb-8323-0d6721fd2af4.jpg)
![IMG_20180525_200436](https://user-images.githubusercontent.com/596579/123939971-01e5e780-d999-11eb-8923-99d753492074.jpg)
![IMG_20180527_162437](https://user-images.githubusercontent.com/596579/123939976-03171480-d999-11eb-863f-2e9e90fd5308.jpg)
![IMG_20180527_172211](https://user-images.githubusercontent.com/596579/123939982-05796e80-d999-11eb-851f-bfb59a3fd767.jpg)
![IMG_20180803_132027948_HDR](https://user-images.githubusercontent.com/596579/123939998-07dbc880-d999-11eb-9518-051c988932ad.jpg)
![IMG_20180803_201431856](https://user-images.githubusercontent.com/596579/123940002-090cf580-d999-11eb-9b1e-ae5422b7aa70.jpg)
![IMG_20180804_124255099_HDR](https://user-images.githubusercontent.com/596579/123940008-0a3e2280-d999-11eb-8c89-f5093c99b757.jpg)
![IMG_20180804_141804292_HDR](https://user-images.githubusercontent.com/596579/123940015-0c07e600-d999-11eb-9d62-43afbe170396.jpg)
![IMG_20180804_142046763_HDR](https://user-images.githubusercontent.com/596579/123940020-0e6a4000-d999-11eb-90d0-cf831b4f25ca.jpg)
![IMG_20180804_183642405_HDR](https://user-images.githubusercontent.com/596579/123940031-10cc9a00-d999-11eb-8b0a-e8ca7a37697d.jpg)
![IMG_20180805_190221047_HDR](https://user-images.githubusercontent.com/596579/123940038-12965d80-d999-11eb-9199-0ebf526a5926.jpg)
![IMG_20180806_160058368_HDR](https://user-images.githubusercontent.com/596579/123940042-132ef400-d999-11eb-8c45-4683787dba66.jpg)
![IMG_20200905_090233336_MP-COLLAGE](https://user-images.githubusercontent.com/596579/123940046-14f8b780-d999-11eb-863a-fabad53d04de.jpg)
![IMG_20200905_095411033](https://user-images.githubusercontent.com/596579/123940051-1629e480-d999-11eb-9ac1-afd93e8c61fb.jpg)
![IMG_20200905_101658162_HDR](https://user-images.githubusercontent.com/596579/123940065-1924d500-d999-11eb-8117-d369bdcbabeb.jpg)
![IMG_20200905_103356828](https://user-images.githubusercontent.com/596579/123940070-1b872f00-d999-11eb-806b-0195321fbeb9.jpg)
![IMG_20200905_140317804](https://user-images.githubusercontent.com/596579/123940089-1de98900-d999-11eb-9dab-ed035ef86be7.jpg)
![IMG_20200905_142455721_BURST000_COVER_TOP](https://user-images.githubusercontent.com/596579/123940094-1fb34c80-d999-11eb-8a4d-b80912da8a3b.jpg)
![IMG-20170729-WA0004](https://user-images.githubusercontent.com/596579/123940106-217d1000-d999-11eb-8d0a-a69a61eaaf8a.jpg)

**Comment by erivello** [comment]
![saluto-festoso](https://user-images.githubusercontent.com/626131/123974179-b9d8bc00-d9bc-11eb-8d27-260d6e771dc9.jpg)

**Comment by erivello** [comment]
![814511074_12134111612263694195](https://user-images.githubusercontent.com/626131/123974263-c9580500-d9bc-11eb-86c8-52c1c0ea4c67.png)

**Comment by erivello** [comment]
![814511074_12134111612263694195](https://user-images.githubusercontent.com/626131/123974505-f0163b80-d9bc-11eb-97af-e2f90be9338e.jpg)

**Comment by erivello** [comment]
![IMG_20170412_210521](https://user-images.githubusercontent.com/626131/123975269-7cc0f980-d9bd-11eb-8a10-9819535b6ad6.jpg)

**Comment by wutupake** [comment]
Foto trasferite in album Google Photos (link condiviso in separata sede).
L'album è pubblico e modificabile da tutti (almeno finché non si verificheranno dei problemi), tutte le nuove foto andranno caricate lì.
Risolvo :)
